name: Upload to S3

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::339712817572:role/githubActionsRole
        aws-region: us-east-1  # replace with your desired region

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install awscli

    - name: Verify AWS CLI configuration
      run: |
        aws s3 ls

    - name: Sync files to S3
      run: |
        aws s3 sync . s3://your-s3-bucket-name --exclude ".git/*" --delete
